apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Configuration
metadata:
  name: helm-aws-external-dns
  annotations:
    meta.crossplane.io/maintainer: Patrick Lee Scott
    meta.crossplane.io/source: github.com/hops-ops/helm-aws-external-dns
    meta.crossplane.io/description: Installs external-dns with AWS Pod Identity for Route53 DNS record management.
spec:
  dependsOn:
  - function: xpkg.crossplane.io/crossplane-contrib/function-auto-ready
    version: ">=v0.6.0"
  - configuration: ghcr.io/hops-ops/helm-external-dns
    version: ">=v0.1.0"
  - configuration: ghcr.io/hops-ops/aws-pod-identity
    version: ">=v0.5.0"
